name: build

on:
  - push
  - pull_request

jobs:
  buildCRA:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - run: npm i # There is a bug with npm ci -> https://github.com/npm/cli/issues/558
      - run: npm run generate-cra
      - run: npm run lint
        working-directory: generated-cra-app
      - run: npm run checkTs
        working-directory: generated-cra-app
      - run: npm run test:generators:cra
      - run: npm run cleanExampleApp
        working-directory: generated-cra-app
      - run: npm run lint
        working-directory: generated-cra-app
      - run: npm run checkTs
        working-directory: generated-cra-app

