name: build

on:
  - push
  - pull_request

jobs:
  buildCRA:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - run: npm i # There is a bug with npm ci -> https://github.com/npm/cli/issues/558
      - run: npm run generate-cra
  
  testCRA:
    needs: buildCRA
    defaults:
      run:
        working-directory: ./generated-cra-app
    steps:
      - run: npm run test:generators:cra
        working-directory: ../
      - run: npm run lint
      - run: npm run checkTs
      - run: npm run cleanExampleApp
      - run: npm run lint
      - run: npm run checkTs

